server:
  port: 8761
spring:
  application:
    name: naming-server
  management:
    tracing:
      sampling:
        probability: 1.0  # produção 0.05
  zipkin:
    base-url: ${SPRING_ZIPKIN_BASEURL:http://localhost:9411}
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
