name: Microservices Continuous Deployment with Github Actions

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Setup Java 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin' # See 'Supported distributions' for available options
          cache: maven
      - name: Build Eureka Naming Server Docker Image
        working-directory: ./naming-server
        run: mvn spring-boot:build-image 
      - name: Build API Gateway Docker Image
        working-directory: ./api-gateway
        run: mvn spring-boot:build-image 

      - name: Build Exchange Microservice Docker Image
        working-directory: ./exchange.service
        run: mvn clean package 
      - name: Build Book Microservice Docker Image
        working-directory: ./book.service
        run: mvn clean package 

      - name: Docker Compose Build 
        working-directory: ./
        run: docker compose build 
